name = "FungAGE Lab"
license = "MIT"
licenselink = "https://github.com/vogan-lab/blob/main/LICENSE.md"
description = "Fungal Accessory Genome Evolution Research at Uppsala University"
homepage = "https://FungAGE.github.io/"
tags = ["academic",
        "university",
        "research",
        "evolution"
        ]
[author]
  name = "Aaron Vogan"
