name = "Vogan Lab"
license = "MIT"
licenselink = "https://github.com/vogan-lab/blob/main/LICENSE.md"
description = "The Vogan Lab researches fungal evolution/genetics/genomics at Uppsala University, investigating accessory genomes of Fusarium and giant TEs."
homepage = "https://vogan-lab.github.io/"
tags = ["academic",
        "university",
        "research",
        ]
[author]
  name = "Aaron Vogan"
